### ISSUE TITLE
Module 'data_generation' puzzling me. Does it prepare the dataset for 'parsing_network'?

### ISSUE THREAD

**Issue by donghaoye** [MVIG-SJTU/WSHP#1]

**Comment by Fang-Haoshu** [comment]
Hi, yes, it's the method that we generalize data, which is described in our paper

**Comment by donghaoye** [comment]
I still puzzling about  module: 'parsing_network'.
It just a baseline model?

**Comment by Fang-Haoshu** [comment]
What do you mean by "baseline model"?

**Comment by donghaoye** [comment]
'baseline model'  which is you compare with.

**Comment by Fang-Haoshu** [comment]
No, it's our final model.

**Comment by donghaoye** [comment]
enen.
The semantic part segmentation results can be used as extra training data to train a human parsing network without keypoint annotations.

I get it.

THKs
