### ISSUE TITLE
Cannot find the pretrained model in models/final_model/ ?

### ISSUE THREAD

**Issue by ChunfeiMa** [MVIG-SJTU/WSHP#12]
I just cannot find the pretrained model since there is not any directory named models/final_model/.

**Comment by noumanriazkhan** [comment]
You need to download and unzip it from [here](https://jbox.sjtu.edu.cn/l/3Jv9XR) or [here](http://mvig.sjtu.edu.cn/publications/wshp/models.zip).

**Comment by ChunfeiMa** [comment]
@noumanriazkhan  thanks a lots!
