### ISSUE TITLE
basestring not defined

### ISSUE THREAD

**Issue by dht7166** [MVIG-SJTU/WSHP#14]
As title, when running the code for inferencing, I got an error 
`\WSHP\parsing_network\kaffe\tensorflow\network.py", line 78, in feed
    if isinstance(fed_layer, basestring):
NameError: name 'basestring' is not defined`

I take a quick look at the code, and I indeed did not find any reference to the string from elsewhere. What is this error?

Also can I run the model without specifying the mask in the data_list

**Comment by Fang-Haoshu** [comment]
seems an error in tensorflow?

**Comment by noumanriazkhan** [comment]
That's python3 error throwing error for python2 code.

**Comment by dht7166** [comment]
Yeah it is. Thanks for the comment.
