### ISSUE TITLE
can you share your trained model? 

### ISSUE THREAD

**Issue by lsy978745722** [MVIG-SJTU/WSHP#16]

**Comment by noumanriazkhan** [comment]
It's already shared.
https://jbox.sjtu.edu.cn/link/view/80801f89e5a84482842ba6f483584087

**Comment by Fang-Haoshu** [comment]
Thanks @noumanriazkhan 
@lsy978745722  Please refer to https://github.com/MVIG-SJTU/WSHP/tree/master/parsing_network#preparation
