### ISSUE TITLE
why the demo data is not origin_images??? bash demo.sh is not work

### ISSUE THREAD

**Issue by Easyfeng222** [MVIG-SJTU/WSHP#18]

**Comment by Easyfeng222** [comment]
And I want to konw how to use the pascalPose.csv

**Comment by Easyfeng222** [comment]
bash demo.sh

('length of json_dict', 2)
('length of pascal_img', 644)
Traceback (most recent call last):
  File "crop_pose_and_generate_testing_prior.py", line 83, in <module>
    if max_x > origin_img.shape[1] or max_y > origin_img.shape[0]-1:
AttributeError: 'NoneType' object has no attribute 'shape'
------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ../examples
dataroot: .././examples/outputs/crop_output
dataset_mode: single
display_id: 0
display_port: 8097
display_winsize: 256
fineSize: 256
gpu_ids: [0]
how_many: inf
init_type: normal
input_nc: 6
isTrain: False
loadSize: 286
max_dataset_size: inf
model: test
nThreads: 2
n_layers_D: 3
name: pretrained_model
ndf: 64
ngf: 64
no_dropout: False
no_flip: False
norm: instance
ntest: inf
output_nc: 1
phase: test
resize_or_crop: resize_and_crop
results_dir: ../examples
serial_batches: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: unet_256
-------------- End ----------------
CustomDatasetDataLoader
dataset [SingleDataset] was created
test
initialization method [normal]
/home/feng/WSHP/data_generation/refinement_network/models/networks.py:16: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, 0.0, 0.02)
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    model = create_model(opt)
  File "/home/feng/WSHP/data_generation/refinement_network/models/models.py", line 14, in create_model
    model.initialize(opt)
  File "/home/feng/WSHP/data_generation/refinement_network/models/test_model.py", line 21, in initialize
    self.load_network(self.netG, 'G', which_epoch)
  File "/home/feng/WSHP/data_generation/refinement_network/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for UnetGenerator:
	Unexpected running stats buffer(s) "model.model.1.model.2.running_mean" and "model.model.1.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.2.running_mean" and "model.model.1.model.3.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.2.running_mean" and "model.model.1.model.3.model.3.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.2.running_mean" and "model.model.1.model.3.model.3.model.3.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.3.model.2.running_mean" and "model.model.1.model.3.model.3.model.3.model.3.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.3.model.3.model.2.running_mean" and "model.model.1.model.3.model.3.model.3.model.3.model.3.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.4.running_mean" and "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.4.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.3.model.3.model.6.running_mean" and "model.model.1.model.3.model.3.model.3.model.3.model.3.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.3.model.6.running_mean" and "model.model.1.model.3.model.3.model.3.model.3.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.6.running_mean" and "model.model.1.model.3.model.3.model.3.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.6.running_mean" and "model.model.1.model.3.model.3.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.6.running_mean" and "model.model.1.model.3.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.6.running_mean" and "model.model.1.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
Traceback (most recent call last):
  File "merge_parsing_result.py", line 43, in <module>
    all_prior = np.zeros(origin_img.shape, dtype=np.uint8)
AttributeError: 'NoneType' object has no attribute 'shape'
feng@feng-Precision-Tower-5810:~/WSHP/data_generation$ bash demo.sh
('length of json_dict', 2)
('length of pascal_img', 644)
('bbox', [273, 0, 461, 611])
(0, 'picked pascal', '2010_001619_4')
(1, 'picked pascal', '2010_003117_0')
(2, 'picked pascal', '2008_008066_0')
(u'COCO_train2014_000000036827.jpg', 0, 1)
('bbox', [308, 272, 331, 406])
(0, 'picked pascal', '2010_003117_0')
(1, 'picked pascal', '2008_001784_1')
(2, 'picked pascal', '2010_003508_0')
(u'COCO_train2014_000000131780.jpg', 0, 2)
('bbox', [122, 261, 160, 410])
(0, 'picked pascal', '2010_004601_0')
(1, 'picked pascal', '2008_007525_2')
(2, 'picked pascal', '2008_001911_6')
(u'COCO_train2014_000000131780.jpg', 1, 2)
('bbox', [370, 256, 429, 423])
(0, 'picked pascal', '2010_001408_1')
(1, 'picked pascal', '2008_007409_0')
(2, 'picked pascal', '2010_003936_0')
(u'COCO_train2014_000000131780.jpg', 2, 2)
('bbox', [343, 271, 390, 417])
(0, 'picked pascal', '2008_001294_1')
(1, 'picked pascal', '2010_004601_0')
(2, 'picked pascal', '2008_000971_1')
(u'COCO_train2014_000000131780.jpg', 3, 2)
finished
------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ../examples
dataroot: .././examples/outputs/crop_output
dataset_mode: single
display_id: 0
display_port: 8097
display_winsize: 256
fineSize: 256
gpu_ids: [0]
how_many: inf
init_type: normal
input_nc: 6
isTrain: False
loadSize: 286
max_dataset_size: inf
model: test
nThreads: 2
n_layers_D: 3
name: pretrained_model
ndf: 64
ngf: 64
no_dropout: False
no_flip: False
norm: instance
ntest: inf
output_nc: 1
phase: test
resize_or_crop: resize_and_crop
results_dir: ../examples
serial_batches: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: unet_256
-------------- End ----------------
CustomDatasetDataLoader
dataset [SingleDataset] was created
test
initialization method [normal]
/home/feng/WSHP/data_generation/refinement_network/models/networks.py:16: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, 0.0, 0.02)
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    model = create_model(opt)
  File "/home/feng/WSHP/data_generation/refinement_network/models/models.py", line 14, in create_model
    model.initialize(opt)
  File "/home/feng/WSHP/data_generation/refinement_network/models/test_model.py", line 21, in initialize
    self.load_network(self.netG, 'G', which_epoch)
  File "/home/feng/WSHP/data_generation/refinement_network/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for UnetGenerator:
	Unexpected running stats buffer(s) "model.model.1.model.2.running_mean" and "model.model.1.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.2.running_mean" and "model.model.1.model.3.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.2.running_mean" and "model.model.1.model.3.model.3.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.2.running_mean" and "model.model.1.model.3.model.3.model.3.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.3.model.2.running_mean" and "model.model.1.model.3.model.3.model.3.model.3.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.3.model.3.model.2.running_mean" and "model.model.1.model.3.model.3.model.3.model.3.model.3.model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.4.running_mean" and "model.model.1.model.3.model.3.model.3.model.3.model.3.model.3.model.4.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.3.model.3.model.6.running_mean" and "model.model.1.model.3.model.3.model.3.model.3.model.3.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.3.model.6.running_mean" and "model.model.1.model.3.model.3.model.3.model.3.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.3.model.6.running_mean" and "model.model.1.model.3.model.3.model.3.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.3.model.6.running_mean" and "model.model.1.model.3.model.3.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.3.model.6.running_mean" and "model.model.1.model.3.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
	Unexpected running stats buffer(s) "model.model.1.model.6.running_mean" and "model.model.1.model.6.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
bbox [273, 0, 461, 611]
Traceback (most recent call last):
  File "merge_parsing_result.py", line 87, in <module>
    prior = cv2.resize(prior, (bbox[2]+1-bbox[0], bbox[3]+1-bbox[1]), interpolation=cv2.INTER_NEAREST)
cv2.error: OpenCV(3.4.4) /io/opencv/modules/imgproc/src/resize.cpp:3784: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by luguansong** [comment]
You can refer to #10 and our readme. This code should run using pytorch0.3.0.

Just put pascalPose.csv in ./examples, it will be used by python script crop_pose_and_generate_testing_prior.py.
