### ISSUE TITLE
What the data_list stand for?

### ISSUE THREAD

**Issue by guymcmusker** [MVIG-SJTU/WSHP#23]
Hi, I've downloaded the pretrained model and I was trying to segment some images. The problem is that in the repositoryt isn't any data-list example. In the codebase there is a reference to dataset/dance.txt but I didn't find it anywhere.
Where can I find this data list fileor How can I generate it?

**Comment by Fang-Haoshu** [comment]
Hi, it is the image list for your images

**Comment by guymcmusker** [comment]
Think you.
A txt with one image filenamw per line?


Il Lun 5 Ago 2019, 13:15 Fred Fang <notifications@github.com> ha scritto:

**Comment by Fang-Haoshu** [comment]
Hi, I think so. You can take a try:D
