### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'Dimension' and 'int'

### ISSUE THREAD

**Issue by NguyenDangBinh** [MVIG-SJTU/WSHP#24]
dear,
I had the errors above.
What version did you use python, tensorflow? Tensorflow =1.1?

**Comment by NguyenDangBinh** [comment]
I knew it. The reason is the version of python and tensorflow.

**Comment by anibaljasin** [comment]
Which is the python version to use?

**Comment by ElephantGit** [comment]
> Which is the python version to use?

python2
