### ISSUE TITLE
about pretrained model

### ISSUE THREAD

**Issue by dickkky** [MVIG-SJTU/WSHP#34]
Could you tell me where can I download pretrained model? What's meaning of data_list in code "DATA_LIST = './dataset/dance.txt'"? thx.

**Comment by Fang-Haoshu** [comment]
oh hi, the txt is the image list you want to run. The pretrained model can be found at https://jbox.sjtu.edu.cn/l/hJjgjw

**Comment by dickkky** [comment]
Thanks for your reply !

发自我的iPhone

**Comment by et148** [comment]
> oh hi, the txt is the image list you want to run. The pretrained model can be found at https://jbox.sjtu.edu.cn/l/hJjgjw

why can't i open this link?

**Comment by Alex-yh97** [comment]
Could you please tell me where can i download the pre-trained model ? i cannot open the link which you put in the project.
Thank you very much

**Comment by xqneko** [comment]
> oh hi, the txt is the image list you want to run. The pretrained model can be found at https://jbox.sjtu.edu.cn/l/hJjgjw

The link provided is still not accessible. Would you please provide the pretrained models on other platforms, such as Google Drive, like another project in your group called AlphaPose did please? 

Thank you.

**Comment by Fang-Haoshu** [comment]
Baidu Pan: https://pan.baidu.com/s/1AoGJbZ4YHEbV0x89K1-8nQ 
code：r0yb 

Gdrive: https://drive.google.com/file/d/1aPb2rilhYestHL_7jJglmCHv7ScIG8MQ/view?usp=sharing

Hi folks, seems the Jbox from SJTU does not allow IP outside of SJTU anymore. I upload the models to Baidu Pan and Google Drive

**Comment by ms-xie** [comment]
Hi, Would you please provide the dataset on other platforms, such as Google Drive or Baidu Pan?
The link : [https://jbox.sjtu.edu.cn/l/H1Nwz8](https://jbox.sjtu.edu.cn/l/H1Nwz8) is not accessible.


Thank you.

**Comment by ms-xie** [comment]
你好，我是清华大学的学生，由于dataset 在交大云盘 https://jbox.sjtu.edu.cn/l/H1Nwz8 外网无法访问，想请问能转传百度云盘或google drive吗?谢谢!

**Comment by Fang-Haoshu** [comment]
Hi @ms-xie , thanks for your interest! In fact, I was trying to. But a problem is that the data is too large (~20GB) and my laptops did not have enough space to save it. I just got a new laptop and will try to update it.

**Comment by Fang-Haoshu** [comment]
link: https://pan.baidu.com/s/1ywqpcsvPTsjIY_Slsl9Zhg 
code: 6wqq
