### ISSUE TITLE
Realtime issue

### ISSUE THREAD

**Issue by kai0122** [MVIG-SJTU/WSHP#7]
Hi, 
Can I run this code for realtime video from webcam?
Thank you :)

**Comment by Fang-Haoshu** [comment]
Hi, the detection time is realtime, but I haven't added the webcam support. Perhaps you can make a pull request. It's not very difficult:D

**Comment by kai0122** [comment]
Thank you! Since I am using my MacBook running the inference.py file, my time per jpg image is 20 second. Maybe if I change to a better environment, it will be realtime. :)

**Comment by noumanriazkhan** [comment]
No real time benchmark in your results though but what could be some ways to speed up the trained network? The backbone here is ResNet, for Mobilenet backbone, what could be possible changes to code?

**Comment by Fang-Haoshu** [comment]
Hi, sure it's possible. Or you can also try U-Net or SegNet for realtime segmentation. You can use our released dataset to train the network.
